name: Workflow Run Deploy Test

on:
  push:
    branches:
      - main
    paths:
      - devops/dummy.txt

  workflow_run:
    workflows:
      - "Workflow Run Build Test"
    types:
      - completed

jobs:
  test-success:
    name: Test success
    runs-on: ubuntu-latest
    if: |
      ( ${{ github.event_name == 'workflow_run' }} && ${{ github.event.workflow_run.conclusion == 'success' }} ) ||
      ${{ github.event_name == 'push' }}
    steps:
      - run: echo "This is a step to test workflow runs."
